[package]
edition = "2021"
license = "apache-2.0"
name = "subdir"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
colored = "2.1.0"
dotenv = "0.15.0"
regex = "1.10.3"
